### ISSUE TITLE
Change SIR function

### ISSUE THREAD

**Issue by gh0stwin** [ghosw/crc-project#1]
- [x] Change SIR simulation to a class (#5)
- [x] Test SIR class (#7)
- [x] Create a class to handle running sir simulations and storing results (#9)
